### ISSUE TITLE
define-advice causing issues in Emacs 24.4 and 24.5

### ISSUE THREAD

**Issue by purcell** [emacscollective/auto-compile#19]
The recent change in advice seems to cause issues in 24.4 and 24.5, which I noticed because my [`emacs.d` Travis build](https://travis-ci.org/purcell/emacs.d/builds/473475812) is failing on those versions with the following error:

```
Lisp error: (void-variable byte-compile-log-warning)
q\210T\211)$\207" [byte-compile-log-warning &optional _fill _level auto-compile auto-compile-file-buffer make-variable-buffer-local auto-compile-warnings define-advice :before _string "Increment local value of `auto-compile-warnings'."] 7)
  auto-compile-on-load-mode()
```

Newer versions are fine. Maybe define-advice was broken in those earlier `nadvice` versions?

**Comment by tarsius** [comment]
Turns out `define-advice` wasn't added until 25.1. Time to officially drop support for 24, I'm afraid.

**Comment by purcell** [comment]
Aww. You could just use `advice-add`, though, no?
