### ISSUE TITLE
Skip directory

### ISSUE THREAD

**Issue by manuel-uberti** [emacscollective/auto-compile#21]
Hi,

first of all thanks for this package.

This is more of a feature request than an issue, because `auto-compile` works as expected when I set it up according to the instructions in the README.

One thing I'd like to understand is whether there is a chance to avoid compiling a specific directory in my configuration. To clarify: I'd only want `auto-compile` to work on the directory containing my configuration files, and leave the rest of `.emacs.d` untouched.

Note that I am already excluding `early-init.el` and `init.el` from byte-compilation.

**Comment by tarsius** [comment]
Auto-compile only *updates* the `*.elc` files. If there is no `*.elc` file already, then it does not create it. Is that not enough for your use-case? I cannot imagine a case where you actually *want* to keep outdated `*.elc` files around instead of *updating* them.

**Comment by manuel-uberti** [comment]
It's not about outdated `*.elc` files, it's about ensuring my files (and only those files) are at least compiled once.

So I need at least one byte-compilation before `auto-compile` can do its work, is this correct?

**Comment by manuel-uberti** [comment]
To add a bit of context: I have Ansible Playbooks which set up my machines every time I change OS. I want to ensure my Emacs configuration is ready to go after those Ansible Playbooks have completed.

The question then is: should I byte-compile what I need from there, or is `auto-compile` taking care of it when I start Emacs? From your reply, I understand `auto-compile` needs `*.elc` files to work on.

**Comment by tarsius** [comment]
> The question then is: should I byte-compile what I need from there, or is `auto-compile` taking care of it when I start Emacs? From your reply, I understand `auto-compile` needs `*.elc` files to work on.

Yes, you have to do it yourself. Auto-compile only updates existing `*.elc` when the corresponding `*.el` files is saved or loaded. There's one exception: the command `toggle-auto-compile` (which see) can be used to explicitly stop/start compiling one/multiple files. But that's intended for interactive use; you should probably use something like `byte-recompile-directory` instead.

**Comment by manuel-uberti** [comment]
Perfect. Thank you for the clarification.

**Comment by tarsius** [comment]
You might still have to figure out how to exclude subdirectories. `byte-recompile-directory ` works recursively I think.

**Comment by manuel-uberti** [comment]
Yes, but that's no problem because the files I want to byte-compile are in one specific directory.
