### ISSUE TITLE
auto-compile self check

### ISSUE THREAD

**Issue by JAremko** [emacscollective/auto-compile#22]
What if someone accidentally compiled `auto-compile.el`  and `packed.el`. Will they go stale forever?  Maybe  `auto-compile` can do some kind of a self check during the first load :thinking:

**Comment by tarsius** [comment]
These libraries are compiled *on purpose* by `package.el` or `make all` or whatever mechanism for installing packages is used. Once a new version of these libraries are installed then the respective `*.elc` files of course should also be regenerated and doing so may fail without the user noticing that. In that cast Auto-compile will indeed fail to notice the issue. There is nothing that can be done about it.
